# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('videodate', models.DateField(null=True)),
            ],
        ),
    ]
