# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstream', '0002_auto_20160613_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='url',
            field=models.TextField(max_length=1000),
        ),
    ]
